extern char *biosfile;
extern float timercomp;
extern int16_t adlibgensample(void);
extern int16_t getBlasterSample(void);
extern int16_t getssourcebyte(void);
extern int16_t speakergensample(void);
extern int32_t latency;
extern int32_t usesamplerate;
extern int  initscreen (const char *ver);
extern int ne2000_can_receive(void);
extern uint16_t cols;
extern uint16_t constanth;
extern uint16_t constantw;
extern uint16_t cursorposition;
extern uint16_t cursorvisible;
extern uint16_t cursx;
extern uint16_t cursy;
extern uint16_t oldh;
extern uint16_t oldw;
extern uint16_t portin16(uint16_t portnum);
extern uint16_t rows;
extern uint16_t	segregs[4];
extern uint16_t segregs[4];
extern uint16_t VGA_ATTR[0x100];
extern uint16_t VGA_CRTC[0x100];
extern uint16_t VGA_GC[0x100];
extern uint16_t vgapage;
extern uint16_t VGA_SC[0x100];
extern uint16_t vtotal;
extern uint32_t framedelay;
extern uint32_t loadrom (uint32_t addr32, const char *filename, uint8_t failure_fatal);
extern uint32_t makeupticks;
extern uint32_t nh;
extern uint32_t nw;
extern uint32_t palettecga[16];
extern uint32_t palettevga[256];
extern uint32_t speed;
extern uint32_t textbase;
extern uint32_t usefullscreen;
extern uint32_t usegrabmode;
extern uint32_t videobase;
extern uint32_t x;
extern uint32_t y;
extern uint64_t curtick;
extern uint64_t gensamplerate;
extern uint64_t hostfreq;
extern uint64_t lasttick;
extern uint64_t sampleticks;
extern uint64_t tickgap;
extern uint64_t timinginterval;
extern uint64_t totalexec;
extern uint64_t totalframes;
extern uint8_t blankattr;
extern uint8_t bootdrive;
extern uint8_t cf;
extern uint8_t cgabg;
extern uint8_t cgaonly;
extern uint8_t clocksafe;
extern uint8_t doaudio;
extern uint8_t ethif;
extern uint8_t fontcga[32768];
extern uint8_t hdcount;
extern uint8_t inadlib (uint16_t portnum);
extern uint8_t insertdisk (uint8_t drivenum, char *filename);
extern uint8_t keyboardwaitack;
extern uint8_t net_enabled;
extern uint8_t nextintr(void);
extern uint8_t noscale;
extern uint8_t nosmooth;
extern uint8_t port3da;
extern uint8_t port6;
extern uint8_t portin(uint16_t portnum);
extern uint8_t portram[0x10000];
extern uint8_t RAM[0x100000];
extern uint8_t read8237 (uint8_t channel);
extern uint8_t read86 (uint32_t addr32);
extern uint8_t readonly[0x100000];
extern uint8_t readVGA(uint32_t addr32);
extern uint8_t renderbenchmark;
extern uint8_t running;
extern uint8_t scrmodechange;
extern uint8_t slowsystem;
extern uint8_t speakerenabled;
extern uint8_t updatedscreen;
extern uint8_t useconsole;
extern uint8_t usessource;
extern uint8_t verbose;
extern uint8_t vidcolor;
extern uint8_t vidgfxmode;
extern uint8_t vidmode;
extern uint8_t VRAM[262144];
extern void bufsermousedata (uint8_t value);
extern void diskhandler(void);
extern void dispatch(void);
extern void doirq (uint8_t irqnum);
extern void doscrmodechange(void);
extern void ejectdisk (uint8_t drivenum);
extern void exec86 (uint32_t execloops);
extern void handleinput(void);
extern void init8237(void);
extern void initadlib (uint16_t baseport);
extern void initBlaster (uint16_t baseport, uint8_t irq);
extern void initpcap(void);
extern void initsermouse (uint16_t baseport, uint8_t irq);
extern void initsoundsource(void);
extern void inittiming(void);
extern void initVideoPorts(void);
extern void isa_ne2000_init (uint16_t baseport, uint8_t irq);
extern void killaudio(void);
extern void ne2000_receive (const uint8_t *buf, int size);
extern void nethandler(void);
extern void outadlib (uint16_t portnum, uint8_t value);
extern void parsecl (int argc, char *argv[]);
extern void portout16(uint16_t portnum, uint16_t value);
extern void portout(uint16_t portnum, uint8_t value);
extern void *port_read_callback[0x10000];
extern void *port_read_callback16[0x10000];
extern void *port_write_callback[0x10000];
extern void *port_write_callback16[0x10000];
extern void readdisk(uint8_t drivenum, uint16_t dstseg, uint16_t dstoff, uint16_t cyl, uint16_t sect, uint16_t head, uint16_t sectcount);
extern void reset86(void);
extern uint8_t dohardreset;
extern void sendpkt (uint8_t *src, uint16_t len);
extern void sermouseevent (uint8_t buttons, int8_t xrel, int8_t yrel);
extern void set_port_read_redirector (uint16_t startport, uint16_t endport, void *callback);
extern void set_port_read_redirector(uint16_t startport, uint16_t endport, void *callback);
extern void set_port_write_redirector (uint16_t startport, uint16_t endport, void *callback);
extern void set_port_write_redirector(uint16_t startport, uint16_t endport, void *callback);
extern void setwindowtitle (const char *extra);
extern void tickadlib(void);
extern void tickaudio(void);
extern void tickBlaster(void);
extern void tickssource(void);
extern void timing(void);
extern void vidinterrupt(void);
extern void write86 (uint32_t addr32, uint8_t value);
extern void writeVGA(uint32_t addr32, uint8_t value);

